/*
 * GoogleKeep CodingChallenge APIs
 *
 * This is a sample server
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ErrorCode int32

const (
	InvalidInput int32 = 1001
	LoginFailed
	TokenParseFailed
	RepoFetchFailed
)

// Error - Error returned by server
type Error struct {
	TraceId string `json:"traceId,omitempty"`

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}

func NewError(Code int32, Message string) Error {
	return Error{Code: Code, Message: Message}
}
