/*
 * GoogleKeep APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type User struct {
	// ID is the unique identifier for a user
	ID string `json:"_id,omitempty" bson:"_id"`

	// Username is the username this is same as ID
	Username string `json:"username,omitempty" bson:"username"`

	// NoteIDs is a list of Note IDs which is stored/retrieved from Note repo
	NoteIDs []string `json:"notes,omitempty" bson:"notes"`
}
